### Test for readiness
GET http://rbc.dev/api/ping


### Users
POST http://rbc.dev/api/users


### PROD: Test for readiness
GET https://api.curiouscommunities.net/api/ping


### STAGING: Test for readiness
GET http://api-staging.curiouscommunities.net/api/ping
